### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by Marlysson** [niltoncsr/numeros#1]
What you think about tests in this project , to facilitates contributing ..

Because I gone analyse the code then had many slicing , that make it difficult to think in some cases that they would be applicated.

**Comment by niltoncsr** [comment]
Exactlly, @Marlysson! Actually it's a to-do topic on README, and I am deciding what tool to use... I am willing to try Jasmine for the first time. Do you think it's appopriate?
Any help is more than welcome :smiley:

**Comment by Marlysson** [comment]
Great , I still don't know tests in javascript , but jasmine seems appropriate tool for this.. 
Has the Mocha too ..

**Comment by niltoncsr** [comment]
Yeah, we have some tools that can make the job, but I didn't  played with them before either 😅
So we can play freely! Jasmine seems fine to me, so, whatever for now. Let's rock it! :smiley:

**Comment by niltoncsr** [comment]
I'll add some basic coverage in this [PR](https://github.com/niltoncsr/numeros/pull/2), @Marlysson.
Do you wanna check it out?! It can be a nice way for both of us getting into testing tools.

**Comment by niltoncsr** [comment]
I think this project in this state has a good test coverage. What are your thoughts, @Marlysson?

**Comment by Marlysson** [comment]
Wow, I saw the code now..
It's wondeful , many tests cases..with many numbers.. 
Now are good to handle the code without break them :smile: 

Great!!
